services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: photo_album
      POSTGRES_USER: photo_album
      POSTGRES_PASSWORD: photo_album
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: